### ISSUE TITLE
Duda consumo de toquen API.

### ISSUE THREAD

**Issue by RmG152** [figorr/meteocat#1]
Actualmente, con otras integraciones, utilizo el siguiente código para informar un sensor donde almaceno la información de clima por hora:
```
  - trigger:
      - trigger: time_pattern
        hours: /1
      - trigger: state
        entity_id: weather.aemet
      - trigger: homeassistant
        event: start
      - trigger: event
        event_type: event_template_reloaded
    action:
      - action: weather.get_forecasts
        data:
          type: hourly
        target:
          entity_id: weather.aemet
        response_variable: hourly
    sensor:
      - name: Weather Forecast Hourly Aemet
        unique_id: weather_forecast_hourly_aemet
        state: "{{ now().isoformat() }}"
        attributes:
          forecast: "{{ hourly['weather.aemet'].forecast }}"
```

Me gustaría saber qué toquen se utilizan al utilizar este action ```weather.get_forecasts```, para calcular el intervalo de llamadas para crear un nuevo sensor con meteocat.

Y si es posible, también me gustaría saber más o menos cuantos toquen consume por defecto la integración (una aproximación).
